@echo off
REM setup-cloudflare.bat
REM
REM One-shot setup for the SERVER side of running Stockroom behind
REM Cloudflare. Does:
REM   1. Generates a strong JWT_SECRET (64 hex chars) and writes .env.
REM      Reuses an existing one if present; pass --force to rotate.
REM   2. Starts the Stockroom server on PORT (default 3000) in the
REM      FOREGROUND of this shell. Press Ctrl-C to stop.
REM
REM Does NOT do the Cloudflare side. For that, use trycloudflare.bat
REM (quick tunnel, ephemeral URL) or install-tunnel.bat (named tunnel,
REM stable URL, needs Cloudflare account) — see CLOUDFLARE.md.
REM
REM Usage:
REM   setup-cloudflare.bat            (safe re-run; keeps existing secret)
REM   setup-cloudflare.bat --force    (rotate JWT_SECRET; logs everyone out)
REM   setup-cloudflare.bat 8080       (use a different PORT)

setlocal ENABLEDELAYEDEXPANSION

set "FORCE=0"
set "PORT=%~1"
if /I "%PORT%"=="--force" (
    set "FORCE=1"
    set "PORT=%~2"
)

REM PORT defaults to 3000 if neither arg provided a value.
if "%PORT%"=="" set "PORT=3000"
if /I "%PORT%"=="--force" set "PORT=3000"

cd /d "%~dp0"

echo === Stockroom: server setup ===
echo Port: %PORT%
echo.

REM ---- 1. JWT_SECRET handling ----
set "ENVFILE=%~dp0.env"
set "HAVE_SECRET=0"

if exist "%ENVFILE%" (
    for /f "usebackq tokens=1,2 delims==" %%A in ("%ENVFILE%") do (
        if /I "%%A"=="JWT_SECRET" (
            if not "%%B"=="" set "HAVE_SECRET=1"
        )
    )
)

if "%HAVE_SECRET%"=="1" (
    if "%FORCE%"=="1" (
        echo [..] --force passed: rotating JWT_SECRET. All users will be logged out.
    ) else (
        echo [ok] .env already has a JWT_SECRET. Reusing it. (Pass --force to rotate.)
        goto :start_server
    )
)

echo [..] Generating JWT_SECRET (64 hex chars) ...
REM Avoid `for /f` over the node command — single-quoted parens confuse
REM cmd's parser. Run node first, then read its stdout from a temp file.
set "SECFILE=%LOCALAPPDATA%\Temp\stockroom-jwt-secret.tmp"
node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" > "%SECFILE%" 2>nul
if errorlevel 1 (
    echo [err] node failed to generate JWT_SECRET. Is Node.js on PATH?
    del "%SECFILE%" 2>nul
    exit /b 1
)

set /p NEWSECRET=<"%SECFILE%"
del "%SECFILE%" 2>nul

if not defined NEWSECRET (
    echo [err] JWT_SECRET was empty after generation.
    exit /b 1
)

(
    echo # Generated by setup-cloudflare.bat on %DATE% %TIME%
    echo # 64 hex chars ^(32 bytes^) of cryptographically-random data.
    echo # KEEP THIS SECRET. Sessions stay valid across restarts only
    echo # if the server starts with this SAME value.
    echo JWT_SECRET=%NEWSECRET%
    echo.
    echo # Optional overrides ^(uncomment + edit if needed^):
    echo # NODE_ENV=production
    echo # JWT_TTL=8h
    echo # PORT=3000
) > "%ENVFILE%"

echo [ok] wrote %ENVFILE%
echo.
echo ==========================================================
echo  BACK UP THIS SECRET NOW ^(password manager / secure note^).
echo  Without it, every server restart logs all users out.
echo ==========================================================
echo   JWT_SECRET=%NEWSECRET%
echo ==========================================================
echo.

:start_server
REM Load .env into the current shell so JWT_SECRET is set.
REM Skip blank lines and comments (lines starting with #).
for /f "usebackq tokens=1,2 delims==" %%A in ("%ENVFILE%") do (
    if not "%%A"=="" (
        if not "%%A:~0,1%"=="#" (
            if not "%%B"=="" set "%%A=%%B"
        )
    )
)

if not defined JWT_SECRET (
    echo [err] JWT_SECRET still not set after .env load. Aborting.
    exit /b 1
)

echo [..] Starting Stockroom on http://localhost:%PORT% ...
echo      Press Ctrl-C to stop.
echo.

node server/index.js
